// 主要ライブラリごとの「具体的なオブジェクト」図鑑。
// LIBRARY_CATALOGの各ライブラリが実際にimportされていた場合だけ、
// ここに定義されたパターンでコード全体を走査して個別の関数/フックの使用を検出する。

const REACT_OBJECTS = [
  { key: 'useState', label: 'useState', icon: '🪝', description: '状態(値)を持たせ、更新するとUIを再描画させるフック。', pattern: /\buseState\s*\(/g },
  { key: 'useEffect', label: 'useEffect', icon: '🪝', description: '描画後に副作用(データ取得など)を実行するフック。', pattern: /\buseEffect\s*\(/g },
  { key: 'useContext', label: 'useContext', icon: '🪝', description: '親から渡されたContextの値を読み取るフック。', pattern: /\buseContext\s*\(/g },
  { key: 'useReducer', label: 'useReducer', icon: '🪝', description: '複雑な状態更新をreducer関数でまとめて管理するフック。', pattern: /\buseReducer\s*\(/g },
  { key: 'useMemo', label: 'useMemo', icon: '🪝', description: '計算結果を再利用してムダな再計算を防ぐフック。', pattern: /\buseMemo\s*\(/g },
  { key: 'useCallback', label: 'useCallback', icon: '🪝', description: '関数そのものを再利用してムダな再生成を防ぐフック。', pattern: /\buseCallback\s*\(/g },
  { key: 'useRef', label: 'useRef', icon: '🪝', description: '再描画をまたいで値やDOM要素を保持するフック。', pattern: /\buseRef\s*\(/g },
  { key: 'useLayoutEffect', label: 'useLayoutEffect', icon: '🪝', description: '描画直後、画面反映前に同期的に実行される副作用フック。', pattern: /\buseLayoutEffect\s*\(/g },
  { key: 'useImperativeHandle', label: 'useImperativeHandle', icon: '🪝', description: 'refで公開する内容をカスタマイズするフック。', pattern: /\buseImperativeHandle\s*\(/g },
  { key: 'useTransition', label: 'useTransition', icon: '🪝', description: '重い更新を優先度低めにして体感速度を保つフック。', pattern: /\buseTransition\s*\(/g },
  { key: 'useDeferredValue', label: 'useDeferredValue', icon: '🪝', description: '値の反映を遅延させ、描画のカクつきを抑えるフック。', pattern: /\buseDeferredValue\s*\(/g },
  { key: 'useId', label: 'useId', icon: '🪝', description: 'サーバー/クライアントで一致する一意なIDを生成するフック。', pattern: /\buseId\s*\(/g },
  { key: 'useSyncExternalStore', label: 'useSyncExternalStore', icon: '🪝', description: '外部ストアの値をReactの状態として購読するフック。', pattern: /\buseSyncExternalStore\s*\(/g },
  { key: 'useDebugValue', label: 'useDebugValue', icon: '🪝', description: '開発者ツールにカスタムフックの値を表示するフック。', pattern: /\buseDebugValue\s*\(/g },
  { key: 'useInsertionEffect', label: 'useInsertionEffect', icon: '🪝', description: 'CSS-in-JSライブラリ向けの、描画前に実行される特殊なフック。', pattern: /\buseInsertionEffect\s*\(/g },
  { key: 'react_component', label: 'Component', icon: '🏛️', description: '状態やライフサイクルを持てる、クラス形式のコンポーネントの基底クラス。', pattern: /\bComponent\b/g },
  { key: 'PureComponent', label: 'PureComponent', icon: '🏛️', description: 'propsやstateが変わらなければ再描画しないComponent。', pattern: /\bPureComponent\b/g },
  { key: 'react_fragment', label: 'Fragment', icon: '🧩', description: '余計なDOM要素を増やさずに複数要素をまとめる入れ物。', pattern: /\bFragment\b|<>/g },
  { key: 'StrictMode', label: 'StrictMode', icon: '🔍', description: '開発中に問題のあるコードを検出しやすくするモード。', pattern: /\bStrictMode\b/g },
  { key: 'Suspense', label: 'Suspense', icon: '⏱️', description: '非同期に読み込み中のコンポーネントの代わりに表示を出す仕組み。', pattern: /\bSuspense\b/g },
  { key: 'react_memo', label: 'memo', icon: '🧠', description: 'propsが変わらなければ再描画をスキップする最適化。', pattern: /\bmemo\s*\(/g },
  { key: 'forwardRef', label: 'forwardRef', icon: '➡️', description: '親からのrefを子のDOM要素に転送する仕組み。', pattern: /\bforwardRef\s*\(/g },
  { key: 'react_lazy', label: 'lazy', icon: '🐢', description: 'コンポーネントを必要になるまで読み込みを遅らせる仕組み。', pattern: /\blazy\s*\(/g },
  { key: 'createContext', label: 'createContext', icon: '🌐', description: 'コンポーネントツリー全体で共有できる値(Context)を作る。', pattern: /\bcreateContext\s*\(/g },
  { key: 'createElement', label: 'createElement', icon: '🏗️', description: 'JSXが変換された先にある、要素を作る関数。', pattern: /\bcreateElement\s*\(/g },
  { key: 'cloneElement', label: 'cloneElement', icon: '📄', description: '既存の要素をpropsを変えつつ複製する関数。', pattern: /\bcloneElement\s*\(/g },
  { key: 'createRef', label: 'createRef', icon: '📌', description: 'DOM要素やインスタンスを参照するためのrefオブジェクトを作る(クラス用)。', pattern: /\bcreateRef\s*\(/g },
  { key: 'react_children', label: 'Children', icon: '👶', description: 'props.childrenを安全に操作するためのユーティリティ。', pattern: /\bChildren\./g },
];

const PANDAS_OBJECTS = [
  { key: 'DataFrame', label: 'DataFrame', icon: '📊', description: '表形式のデータを扱う、pandasの中心となるデータ構造。', pattern: /\bDataFrame\s*\(/g },
  { key: 'pd_Series', label: 'Series', icon: '📈', description: '1列分のデータを扱う、pandasの基本データ構造。', pattern: /\bSeries\s*\(/g },
  { key: 'read_csv', label: 'read_csv', icon: '📥', description: 'CSVファイルを読み込んでDataFrameにする。', pattern: /\bread_csv\s*\(/g },
  { key: 'read_excel', label: 'read_excel', icon: '📥', description: 'Excelファイルを読み込んでDataFrameにする。', pattern: /\bread_excel\s*\(/g },
  { key: 'read_json', label: 'read_json', icon: '📥', description: 'JSONを読み込んでDataFrameにする。', pattern: /\bread_json\s*\(/g },
  { key: 'read_sql', label: 'read_sql', icon: '📥', description: 'SQLの実行結果をDataFrameとして読み込む。', pattern: /\bread_sql\s*\(/g },
  { key: 'to_csv', label: 'to_csv', icon: '📤', description: 'DataFrameをCSVファイルとして書き出す。', pattern: /\.to_csv\s*\(/g },
  { key: 'to_excel', label: 'to_excel', icon: '📤', description: 'DataFrameをExcelファイルとして書き出す。', pattern: /\.to_excel\s*\(/g },
  { key: 'pd_merge', label: 'merge', icon: '🔗', description: '共通のキーをもとに2つの表を結合する。', pattern: /\bmerge\s*\(/g },
  { key: 'pd_concat', label: 'concat', icon: '🧵', description: '複数のDataFrame/Seriesを縦や横につなげる。', pattern: /\bconcat\s*\(/g },
  { key: 'groupby', label: 'groupby', icon: '🗂️', description: '特定の列の値でグループ分けして集計する。', pattern: /\.groupby\s*\(/g },
  { key: 'pivot_table', label: 'pivot_table', icon: '🔄', description: '行と列を入れ替えて集計表(ピボットテーブル)を作る。', pattern: /\bpivot_table\s*\(/g },
  { key: 'pd_head', label: 'head', icon: '🔎', description: '先頭の数行だけを取り出して確認する。', pattern: /\.head\s*\(/g },
  { key: 'pd_tail', label: 'tail', icon: '🔎', description: '末尾の数行だけを取り出して確認する。', pattern: /\.tail\s*\(/g },
  { key: 'describe', label: 'describe', icon: '📋', description: '平均・最大・最小などの統計量をまとめて表示する。', pattern: /\.describe\s*\(/g },
  { key: 'pd_info', label: 'info', icon: 'ℹ️', description: '列の型や欠損値の状況などをまとめて表示する。', pattern: /\.info\s*\(/g },
  { key: 'dropna', label: 'dropna', icon: '🧹', description: '欠損値(NaN)を含む行/列を取り除く。', pattern: /\.dropna\s*\(/g },
  { key: 'fillna', label: 'fillna', icon: '🩹', description: '欠損値(NaN)を指定した値で埋める。', pattern: /\.fillna\s*\(/g },
  { key: 'pd_drop', label: 'drop', icon: '✂️', description: '指定した行/列を取り除く。', pattern: /\.drop\s*\(/g },
  { key: 'rename', label: 'rename', icon: '🏷️', description: '列名や行名を変更する。', pattern: /\.rename\s*\(/g },
  { key: 'sort_values', label: 'sort_values', icon: '🔢', description: '値の大きさ順に並べ替える。', pattern: /\.sort_values\s*\(/g },
  { key: 'sort_index', label: 'sort_index', icon: '🔢', description: 'インデックス(行の番号やラベル)順に並べ替える。', pattern: /\.sort_index\s*\(/g },
  { key: 'pd_apply', label: 'apply', icon: '🛠️', description: '各行/列に任意の関数を適用する。', pattern: /\.apply\s*\(/g },
  { key: 'loc', label: 'loc', icon: '📍', description: 'ラベル名で行/列を指定して取り出す。', pattern: /\.loc\[/g },
  { key: 'iloc', label: 'iloc', icon: '📍', description: '位置番号で行/列を指定して取り出す。', pattern: /\.iloc\[/g },
  { key: 'value_counts', label: 'value_counts', icon: '🧮', description: '値ごとの出現回数を数える。', pattern: /\.value_counts\s*\(/g },
  { key: 'pd_unique', label: 'unique', icon: '🔑', description: '重複を除いたユニークな値の一覧を取り出す。', pattern: /\.unique\s*\(/g },
  { key: 'set_index', label: 'set_index', icon: '📌', description: '特定の列を新しいインデックス(行の見出し)に設定する。', pattern: /\.set_index\s*\(/g },
];

const NUMPY_OBJECTS = [
  { key: 'np_array', label: 'array', icon: '🧊', description: 'リストなどからNumPyの配列(ndarray)を作る。', pattern: /\bnp\.array\s*\(/g },
  { key: 'np_zeros', label: 'zeros', icon: '0️⃣', description: '全ての要素が0の配列を作る。', pattern: /\bnp\.zeros\s*\(/g },
  { key: 'np_ones', label: 'ones', icon: '1️⃣', description: '全ての要素が1の配列を作る。', pattern: /\bnp\.ones\s*\(/g },
  { key: 'arange', label: 'arange', icon: '📏', description: '決まった間隔で並ぶ数列の配列を作る。', pattern: /\bnp\.arange\s*\(/g },
  { key: 'linspace', label: 'linspace', icon: '📐', description: '指定した範囲を等間隔に分割した配列を作る。', pattern: /\bnp\.linspace\s*\(/g },
  { key: 'reshape', label: 'reshape', icon: '🔲', description: '配列の形(次元)を変える。', pattern: /\.reshape\s*\(/g },
  { key: 'np_transpose', label: 'transpose', icon: '🔄', description: '行と列を入れ替える(転置する)。', pattern: /\bnp\.transpose\s*\(|\.T\b/g },
  { key: 'np_dot', label: 'dot', icon: '✖️', description: '行列やベクトルの内積を計算する。', pattern: /\bnp\.dot\s*\(/g },
  { key: 'matmul', label: 'matmul', icon: '✖️', description: '行列同士の掛け算(行列積)を計算する。', pattern: /\bnp\.matmul\s*\(/g },
  { key: 'np_sum', label: 'sum', icon: '➕', description: '配列の要素の合計を計算する。', pattern: /\bnp\.sum\s*\(/g },
  { key: 'np_mean', label: 'mean', icon: '📊', description: '配列の要素の平均を計算する。', pattern: /\bnp\.mean\s*\(/g },
  { key: 'np_std', label: 'std', icon: '📊', description: '配列の要素の標準偏差を計算する。', pattern: /\bnp\.std\s*\(/g },
  { key: 'np_var', label: 'var', icon: '📊', description: '配列の要素の分散を計算する。', pattern: /\bnp\.var\s*\(/g },
  { key: 'np_min', label: 'min', icon: '🔽', description: '配列の中の最小値を求める。', pattern: /\bnp\.min\s*\(/g },
  { key: 'np_max', label: 'max', icon: '🔼', description: '配列の中の最大値を求める。', pattern: /\bnp\.max\s*\(/g },
  { key: 'argmax', label: 'argmax', icon: '🎯', description: '最大値がある位置(インデックス)を求める。', pattern: /\bnp\.argmax\s*\(/g },
  { key: 'argmin', label: 'argmin', icon: '🎯', description: '最小値がある位置(インデックス)を求める。', pattern: /\bnp\.argmin\s*\(/g },
  { key: 'np_sort', label: 'sort', icon: '🔢', description: '配列の要素を並べ替える。', pattern: /\bnp\.sort\s*\(/g },
  { key: 'concatenate', label: 'concatenate', icon: '🧵', description: '複数の配列をつなげる。', pattern: /\bnp\.concatenate\s*\(/g },
  { key: 'np_stack', label: 'stack', icon: '📚', description: '複数の配列を新しい軸に沿って積み重ねる。', pattern: /\bnp\.stack\s*\(/g },
  { key: 'np_where', label: 'where', icon: '🔀', description: '条件に応じて値を選ぶ(条件分岐を配列全体に適用)。', pattern: /\bnp\.where\s*\(/g },
  { key: 'np_random', label: 'random', icon: '🎲', description: '乱数を生成するための機能群。', pattern: /\bnp\.random\./g },
  { key: 'np_sqrt', label: 'sqrt', icon: '√', description: '平方根を計算する。', pattern: /\bnp\.sqrt\s*\(/g },
  { key: 'np_exp', label: 'exp', icon: '📈', description: '指数関数(eのべき乗)を計算する。', pattern: /\bnp\.exp\s*\(/g },
];

const EXPRESS_OBJECTS = [
  { key: 'express_factory', label: 'express()', icon: '🚂', description: 'Expressアプリ本体を作成する。', pattern: /\bexpress\s*\(\s*\)/g },
  { key: 'Router', label: 'Router', icon: '🛤️', description: 'ルーティングをまとめて管理する部品を作る。', pattern: /\b(?:express\.)?Router\s*\(/g },
  { key: 'app_get', label: 'app.get', icon: '📥', description: 'GETリクエストに対する処理を登録する。', pattern: /\bapp\.get\s*\(/g },
  { key: 'app_post', label: 'app.post', icon: '📮', description: 'POSTリクエストに対する処理を登録する。', pattern: /\bapp\.post\s*\(/g },
  { key: 'app_put', label: 'app.put', icon: '✏️', description: 'PUTリクエストに対する処理を登録する。', pattern: /\bapp\.put\s*\(/g },
  { key: 'app_delete', label: 'app.delete', icon: '🗑️', description: 'DELETEリクエストに対する処理を登録する。', pattern: /\bapp\.delete\s*\(/g },
  { key: 'app_patch', label: 'app.patch', icon: '🩹', description: 'PATCHリクエストに対する処理を登録する。', pattern: /\bapp\.patch\s*\(/g },
  { key: 'app_use', label: 'app.use', icon: '🧩', description: 'ミドルウェア(共通処理)を組み込む。', pattern: /\bapp\.use\s*\(/g },
  { key: 'app_listen', label: 'app.listen', icon: '👂', description: '指定したポートでサーバーを起動する。', pattern: /\bapp\.listen\s*\(/g },
  { key: 'app_set', label: 'app.set', icon: '⚙️', description: 'アプリ全体の設定値を登録する。', pattern: /\bapp\.set\s*\(/g },
  { key: 'req_body', label: 'req.body', icon: '📦', description: 'リクエストの本文(送信されたデータ)を取得する。', pattern: /\breq\.body\b/g },
  { key: 'req_params', label: 'req.params', icon: '🔗', description: 'URLのパスパラメータを取得する。', pattern: /\breq\.params\b/g },
  { key: 'req_query', label: 'req.query', icon: '❓', description: 'URLのクエリパラメータを取得する。', pattern: /\breq\.query\b/g },
  { key: 'req_headers', label: 'req.headers', icon: '📋', description: 'リクエストのヘッダー情報を取得する。', pattern: /\breq\.headers\b/g },
  { key: 'res_send', label: 'res.send', icon: '📤', description: 'レスポンスを返す(汎用)。', pattern: /\bres\.send\s*\(/g },
  { key: 'res_json', label: 'res.json', icon: '🧾', description: 'JSON形式でレスポンスを返す。', pattern: /\bres\.json\s*\(/g },
  { key: 'res_status', label: 'res.status', icon: '🔢', description: 'HTTPステータスコードを設定する。', pattern: /\bres\.status\s*\(/g },
  { key: 'res_redirect', label: 'res.redirect', icon: '↪️', description: '別のURLへリダイレクトさせる。', pattern: /\bres\.redirect\s*\(/g },
  { key: 'express_next', label: 'next', icon: '⏭️', description: '次のミドルウェア/ハンドラへ処理を渡す。', pattern: /\bnext\s*\(\s*\)/g },
  { key: 'express_static', label: 'express.static', icon: '🗄️', description: '静的ファイル(画像やCSSなど)を配信する。', pattern: /\bexpress\.static\s*\(/g },
  { key: 'express_json', label: 'express.json', icon: '🧾', description: 'JSON形式のリクエストボディを解析するミドルウェア。', pattern: /\bexpress\.json\s*\(/g },
  { key: 'express_urlencoded', label: 'express.urlencoded', icon: '📝', description: 'フォーム送信データを解析するミドルウェア。', pattern: /\bexpress\.urlencoded\s*\(/g },
];

const ELECTRON_OBJECTS = [
  { key: 'BrowserWindow', label: 'BrowserWindow', icon: '🪟', description: 'デスクトップアプリのウィンドウを作成する、Electronの中心的なクラス。', pattern: /\bBrowserWindow\b/g },
  { key: 'ipcMain', label: 'ipcMain', icon: '📨', description: 'レンダラープロセスからのメッセージをメインプロセス側で受け取る仕組み。', pattern: /\bipcMain\b/g },
  { key: 'ipcRenderer', label: 'ipcRenderer', icon: '📩', description: 'メインプロセスへメッセージを送る、レンダラープロセス側の仕組み。', pattern: /\bipcRenderer\b/g },
  { key: 'contextBridge', label: 'contextBridge', icon: '🌉', description: 'レンダラーに安全にAPIを公開する仕組み(preloadスクリプトで使う)。', pattern: /\bcontextBridge\b/g },
  { key: 'electron_Menu', label: 'Menu', icon: '📋', description: 'アプリのメニュー(右クリックメニュー含む)を作る。', pattern: /\bMenu\b/g },
  { key: 'MenuItem', label: 'MenuItem', icon: '🔘', description: 'メニューの中の1項目を表す。', pattern: /\bMenuItem\b/g },
  { key: 'Tray', label: 'Tray', icon: '🗂️', description: 'タスクトレイ(通知領域)にアイコンを常駐させる。', pattern: /\bTray\b/g },
  { key: 'electron_dialog', label: 'dialog', icon: '🗨️', description: 'ファイル選択やメッセージボックスなど、OS標準のダイアログを表示する。', pattern: /\bdialog\./g },
  { key: 'electron_shell', label: 'shell', icon: '🐚', description: '既定のブラウザでURLを開く、ファイルをエクスプローラーで表示するなどOS連携を行う。', pattern: /\bshell\./g },
  { key: 'electron_screen', label: 'screen', icon: '🖥️', description: 'ディスプレイの情報(サイズ・位置)を取得する。', pattern: /\bscreen\./g },
  { key: 'electron_app', label: 'app', icon: '📱', description: 'アプリ全体のライフサイクル(起動・終了・パス取得など)を扱う。', pattern: /\bapp\./g },
  { key: 'electron_session', label: 'session', icon: '🗃️', description: 'Cookieやキャッシュなど、ブラウザセッションの設定を扱う。', pattern: /\bsession\./g },
  { key: 'globalShortcut', label: 'globalShortcut', icon: '⌨️', description: 'OS全体で有効なショートカットキーを登録する。', pattern: /\bglobalShortcut\b/g },
  { key: 'desktopCapturer', label: 'desktopCapturer', icon: '🎥', description: '画面やウィンドウのキャプチャ(スクリーンショット)を取得する。', pattern: /\bdesktopCapturer\b/g },
  { key: 'nativeImage', label: 'nativeImage', icon: '🖼️', description: 'OSネイティブの画像データを扱うクラス。', pattern: /\bnativeImage\b/g },
  { key: 'powerMonitor', label: 'powerMonitor', icon: '🔋', description: 'スリープ状態やアイドル時間など、電源関連のイベントを扱う。', pattern: /\bpowerMonitor\b/g },
  { key: 'autoUpdater', label: 'autoUpdater', icon: '🔄', description: 'アプリの自動アップデート機能を扱う。', pattern: /\bautoUpdater\b/g },
  { key: 'electron_Notification', label: 'Notification', icon: '🔔', description: 'OS標準のデスクトップ通知を表示する。', pattern: /\bNotification\b/g },
  { key: 'electron_clipboard', label: 'clipboard', icon: '📋', description: 'OSのクリップボードの読み書きを行う。', pattern: /\bclipboard\./g },
  { key: 'electron_protocol', label: 'protocol', icon: '🔌', description: '独自のURLスキーム(カスタムプロトコル)を登録する。', pattern: /\bprotocol\./g },
  { key: 'webContents', label: 'webContents', icon: '🌐', description: 'ウィンドウの中身(表示しているWebページ)を操作する。', pattern: /\bwebContents\b/g },
  { key: 'app_whenReady', label: 'app.whenReady', icon: '🚦', description: 'アプリの初期化が完了したタイミングを取得する。', pattern: /\bapp\.whenReady\s*\(/g },
  { key: 'app_quit', label: 'app.quit', icon: '🛑', description: 'アプリを終了する。', pattern: /\bapp\.quit\s*\(/g },
  { key: 'app_getPath', label: 'app.getPath', icon: '📁', description: '設定ファイルの保存場所など、OS標準のディレクトリパスを取得する。', pattern: /\bapp\.getPath\s*\(/g },
];

const JAVASCRIPT_OBJECTS = [
  { key: 'array_map', label: 'Array.map', icon: '🗺️', description: '配列の各要素を変換した新しい配列を作る。', pattern: /\.map\s*\(/g },
  { key: 'array_filter', label: 'Array.filter', icon: '🧹', description: '条件に合う要素だけを残した新しい配列を作る。', pattern: /\.filter\s*\(/g },
  { key: 'array_reduce', label: 'Array.reduce', icon: '➕', description: '配列の要素を1つの値にまとめ上げる。', pattern: /\.reduce\s*\(/g },
  { key: 'array_foreach', label: 'Array.forEach', icon: '🔁', description: '配列の各要素に対して処理を実行する。', pattern: /\.forEach\s*\(/g },
  { key: 'array_find', label: 'Array.find', icon: '🔎', description: '条件に合う最初の要素を探す。', pattern: /\.find\s*\(/g },
  { key: 'array_some', label: 'Array.some', icon: '❓', description: '条件に合う要素が1つでもあるか調べる。', pattern: /\.some\s*\(/g },
  { key: 'array_every', label: 'Array.every', icon: '✅', description: 'すべての要素が条件に合うか調べる。', pattern: /\.every\s*\(/g },
  { key: 'array_includes', label: 'Array.includes', icon: '🔍', description: '配列や文字列に特定の値が含まれるか調べる。', pattern: /\.includes\s*\(/g },
  { key: 'array_sort', label: 'Array.sort', icon: '🔢', description: '配列の要素を並べ替える。', pattern: /\.sort\s*\(/g },
  { key: 'array_flat', label: 'Array.flat', icon: '🫓', description: '多重になった配列を平らにする。', pattern: /\.flat\s*\(/g },
  { key: 'array_flatmap', label: 'Array.flatMap', icon: '🫓', description: 'mapしてからflatする処理をまとめて行う。', pattern: /\.flatMap\s*\(/g },
  { key: 'array_from', label: 'Array.from', icon: '🏗️', description: '配列っぽいものやイテラブルから配列を作る。', pattern: /\bArray\.from\s*\(/g },
  { key: 'object_keys', label: 'Object.keys', icon: '🔑', description: 'オブジェクトのキー一覧を配列で取得する。', pattern: /\bObject\.keys\s*\(/g },
  { key: 'object_values', label: 'Object.values', icon: '💎', description: 'オブジェクトの値一覧を配列で取得する。', pattern: /\bObject\.values\s*\(/g },
  { key: 'object_entries', label: 'Object.entries', icon: '📋', description: 'オブジェクトの[キー,値]の組を配列で取得する。', pattern: /\bObject\.entries\s*\(/g },
  { key: 'object_assign', label: 'Object.assign', icon: '🧩', description: '複数のオブジェクトを1つに合成する。', pattern: /\bObject\.assign\s*\(/g },
  { key: 'object_freeze', label: 'Object.freeze', icon: '🧊', description: 'オブジェクトを変更できないようにする。', pattern: /\bObject\.freeze\s*\(/g },
  { key: 'json_parse', label: 'JSON.parse', icon: '🔓', description: 'JSON文字列をオブジェクトに変換する。', pattern: /\bJSON\.parse\s*\(/g },
  { key: 'json_stringify', label: 'JSON.stringify', icon: '🔒', description: 'オブジェクトをJSON文字列に変換する。', pattern: /\bJSON\.stringify\s*\(/g },
  { key: 'promise_all', label: 'Promise.all', icon: '🤝', description: '複数の非同期処理をまとめて待つ。', pattern: /\bPromise\.all\s*\(/g },
  { key: 'promise_race', label: 'Promise.race', icon: '🏁', description: '複数の非同期処理のうち、最初に終わったものだけを待つ。', pattern: /\bPromise\.race\s*\(/g },
  { key: 'promise_allsettled', label: 'Promise.allSettled', icon: '🧾', description: '複数の非同期処理の結果(成功/失敗問わず)をまとめて待つ。', pattern: /\bPromise\.allSettled\s*\(/g },
  { key: 'js_map', label: 'Map', icon: '🗺️', description: 'キーと値の組を管理するデータ構造。', pattern: /\bnew\s+Map\s*\(/g },
  { key: 'js_set', label: 'Set', icon: '🧺', description: '重複を許さない値の集まりを管理するデータ構造。', pattern: /\bnew\s+Set\s*\(/g },
  { key: 'spread_rest', label: 'スプレッド/レスト構文', icon: '➰', description: '配列/オブジェクトを展開したり、残りをまとめて受け取ったりする記法(...)。', pattern: /\.\.\./g },
  { key: 'optional_chaining', label: 'オプショナルチェーン', icon: '❓', description: '途中の値がnull/undefinedでもエラーにせず安全にアクセスする記法(?.)。', pattern: /\?\./g },
  { key: 'nullish_coalescing', label: 'Null合体演算子', icon: '🎯', description: '値がnull/undefinedのときだけ既定値を使う記法(??)。', pattern: /\?\?/g },
  { key: 'generator_fn', label: 'ジェネレータ関数', icon: '⚡', description: '処理を途中で一時停止・再開できる特殊な関数(function*)。', pattern: /\bfunction\s*\*/g },
];

const TYPESCRIPT_OBJECTS = [
  { key: 'type_alias', label: '型エイリアス(type)', icon: '🏷️', description: '既存の型に別名を付けたり、型を組み合わせたりする(type)。', pattern: /\btype\s+\w+(?:<[^={};]*>)?\s*=/g },
  { key: 'type_assertion', label: '型アサーション(as)', icon: '🎭', description: 'コンパイラに「この値はこの型として扱って」と伝える記法(as)。', pattern: /\bas\s+[A-Z]\w*/g },
  { key: 'readonly_modifier', label: 'readonly', icon: '🔒', description: '一度設定したら変更できないプロパティにする修飾子。', pattern: /\breadonly\b/g },
  { key: 'public_modifier', label: 'public', icon: '🌍', description: 'どこからでもアクセスできるようにする修飾子。', pattern: /\bpublic\s+\w/g },
  { key: 'private_modifier', label: 'private', icon: '🔐', description: 'クラスの内部からしかアクセスできないようにする修飾子。', pattern: /\bprivate\s+\w/g },
  { key: 'protected_modifier', label: 'protected', icon: '🛡️', description: 'クラス自身と継承先からアクセスできるようにする修飾子。', pattern: /\bprotected\s+\w/g },
  { key: 'implements_ts', label: 'implements', icon: '🧩', description: 'クラスが特定のインターフェースの形を満たすことを宣言する。', pattern: /\bimplements\s+\w/g },
  { key: 'abstract_ts', label: 'abstract', icon: '🏗️', description: 'そのままではインスタンス化できない、継承前提のクラス/メソッド。', pattern: /\babstract\s+(class|\w+\()/g },
  { key: 'satisfies_op', label: 'satisfies', icon: '🧪', description: '型を変えずに、値が特定の型に合っているかだけチェックする記法。', pattern: /\bsatisfies\b/g },
  { key: 'keyof_op', label: 'keyof', icon: '🔑', description: 'ある型が持つプロパティ名の集合を、型として取り出す。', pattern: /\bkeyof\b/g },
  { key: 'typeof_type', label: 'typeof(型)', icon: '🔍', description: '変数の型を、その変数自体から取り出す(型の文脈でのtypeof)。', pattern: /:\s*typeof\s+\w/g },
  { key: 'non_null_assertion', label: '非nullアサーション(!)', icon: '❗', description: '「ここはnull/undefinedではない」とコンパイラに伝える記法(!)。', pattern: /\w!(?=[.\s;),])/g },
  { key: 'declare_kw', label: 'declare', icon: '📢', description: '実装を持たない、型情報だけの宣言をする。', pattern: /\bdeclare\s+/g },
  { key: 'partial_utility', label: 'Partial<T>', icon: '🧩', description: 'すべてのプロパティを省略可能にするユーティリティ型。', pattern: /\bPartial</g },
  { key: 'pick_utility', label: 'Pick<T>', icon: '✂️', description: '型から指定したプロパティだけを取り出すユーティリティ型。', pattern: /\bPick</g },
  { key: 'omit_utility', label: 'Omit<T>', icon: '🚫', description: '型から指定したプロパティを除いたものを作るユーティリティ型。', pattern: /\bOmit</g },
  { key: 'record_utility', label: 'Record<K,V>', icon: '📇', description: 'キーと値の型を指定してオブジェクトの型を作るユーティリティ型。', pattern: /\bRecord</g },
  { key: 'required_utility', label: 'Required<T>', icon: '❗', description: 'すべてのプロパティを必須にするユーティリティ型。', pattern: /\bRequired</g },
  { key: 'returntype_utility', label: 'ReturnType<T>', icon: '🔙', description: '関数の戻り値の型を取り出すユーティリティ型。', pattern: /\bReturnType</g },
  { key: 'type_guard', label: '型ガード(is)', icon: '🚧', description: '条件分岐の中で、値の型をより詳しく絞り込む関数の書き方(is)。', pattern: /:\s*\w+\s+is\s+\w+/g },
  { key: 'union_type', label: 'ユニオン型(|)', icon: '🔀', description: '複数の型のうちどれか1つであることを表す型(|)。', pattern: /:\s*\w+(\s*\|\s*\w+)+/g },
  { key: 'unknown_type', label: 'unknown型', icon: '❔', description: 'any同様どんな値も入るが、使う前に型チェックを要求する安全な型。', pattern: /:\s*unknown\b/g },
];

const CPP_OBJECTS = [
  { key: 'std_vector', label: 'vector', icon: '📚', description: '可変長の配列を扱うSTLコンテナ。', pattern: /\bvector\s*</g },
  { key: 'std_map', label: 'map', icon: '🗺️', description: 'キーと値の組を管理するSTLコンテナ(順序付き)。', pattern: /\bmap\s*</g },
  { key: 'std_unordered_map', label: 'unordered_map', icon: '🗺️', description: 'キーと値の組を管理するSTLコンテナ(順序なし・高速)。', pattern: /\bunordered_map\s*</g },
  { key: 'std_set', label: 'set', icon: '🧺', description: '重複を許さない値の集まりを管理するSTLコンテナ。', pattern: /\bset\s*</g },
  { key: 'std_string', label: 'string', icon: '🔤', description: '文字列を扱うSTLのクラス。', pattern: /\bstring\b/g },
  { key: 'std_pair', label: 'pair', icon: '🤝', description: '2つの値を1組にして扱う。', pattern: /\bpair\s*</g },
  { key: 'unique_ptr', label: 'unique_ptr', icon: '📌', description: '所有者が1つだけのスマートポインタ(自動でメモリ解放される)。', pattern: /\bunique_ptr\s*</g },
  { key: 'shared_ptr', label: 'shared_ptr', icon: '🔗', description: '複数箇所で共有できるスマートポインタ。', pattern: /\bshared_ptr\s*</g },
  { key: 'make_unique', label: 'make_unique', icon: '🏗️', description: 'unique_ptrを安全に作るための関数。', pattern: /\bmake_unique\s*</g },
  { key: 'make_shared', label: 'make_shared', icon: '🏗️', description: 'shared_ptrを安全に作るための関数。', pattern: /\bmake_shared\s*</g },
  { key: 'std_sort', label: 'sort', icon: '🔢', description: '範囲の要素を並べ替えるSTLアルゴリズム。', pattern: /\bsort\s*\(/g },
  { key: 'std_find', label: 'find', icon: '🔎', description: '範囲から特定の値を探すSTLアルゴリズム。', pattern: /\bfind\s*\(/g },
  { key: 'push_back', label: 'push_back', icon: '➕', description: 'コンテナの末尾に要素を追加する。', pattern: /\.push_back\s*\(/g },
  { key: 'emplace_back', label: 'emplace_back', icon: '➕', description: 'コンテナの末尾に要素をその場で構築して追加する。', pattern: /\.emplace_back\s*\(/g },
  { key: 'begin_end', label: 'begin/end', icon: '🔁', description: 'コンテナの先頭/末尾を指すイテレータを取得する。', pattern: /\.(begin|end)\s*\(/g },
  { key: 'cout_cin', label: 'cout/cin', icon: '🖨️', description: '標準出力/標準入力を扱うストリームオブジェクト。', pattern: /\b(cout|cin)\b/g },
  { key: 'sizeof_op', label: 'sizeof', icon: '📏', description: '型や変数のメモリ上のサイズ(バイト数)を求める。', pattern: /\bsizeof\s*\(/g },
  { key: 'nullptr_kw', label: 'nullptr', icon: '🈳', description: '何も指していないポインタを表すキーワード。', pattern: /\bnullptr\b/g },
  { key: 'auto_kw', label: 'auto', icon: '🤖', description: 'コンパイラに型を自動推論させるキーワード。', pattern: /\bauto\s+\w+\s*=/g },
  { key: 'static_cast_kw', label: 'static_cast', icon: '🎭', description: 'コンパイル時に安全性を確認しながら型を変換する。', pattern: /\bstatic_cast</g },
  { key: 'dynamic_cast_kw', label: 'dynamic_cast', icon: '🎭', description: '実行時に型を確認しながら、継承関係のある型に変換する。', pattern: /\bdynamic_cast</g },
  { key: 'const_ref', label: '定数参照渡し', icon: '📎', description: 'コピーを避けつつ変更もさせない、読み取り専用の参照渡し。', pattern: /const\s+\w[\w:<>]*\s*&/g },
  { key: 'virtual_fn', label: 'virtual', icon: '🌀', description: '継承先のクラスで上書き(オーバーライド)できる関数。', pattern: /\bvirtual\s+\w/g },
  { key: 'override_kw', label: 'override', icon: '✅', description: '親クラスの仮想関数を確実に上書きしていることを示すキーワード。', pattern: /\boverride\b/g },
];

const CSHARP_OBJECTS = [
  { key: 'linq_select', label: 'Select', icon: '🗺️', description: '各要素を変換する(LINQ)。', pattern: /\.Select\s*\(/g },
  { key: 'linq_where', label: 'Where', icon: '🧹', description: '条件に合う要素だけを残す(LINQ)。', pattern: /\.Where\s*\(/g },
  { key: 'linq_orderby', label: 'OrderBy', icon: '🔢', description: '昇順に並べ替える(LINQ)。', pattern: /\.OrderBy\s*\(/g },
  { key: 'linq_orderbydesc', label: 'OrderByDescending', icon: '🔢', description: '降順に並べ替える(LINQ)。', pattern: /\.OrderByDescending\s*\(/g },
  { key: 'linq_groupby', label: 'GroupBy', icon: '🗂️', description: '特定のキーでグループ分けする(LINQ)。', pattern: /\.GroupBy\s*\(/g },
  { key: 'linq_tolist', label: 'ToList', icon: '📋', description: '結果をListに変換する(LINQ)。', pattern: /\.ToList\s*\(/g },
  { key: 'linq_firstordefault', label: 'FirstOrDefault', icon: '🔎', description: '条件に合う最初の要素、無ければ既定値を取る(LINQ)。', pattern: /\.FirstOrDefault\s*\(/g },
  { key: 'linq_any', label: 'Any', icon: '❓', description: '条件に合う要素が1つでもあるか調べる(LINQ)。', pattern: /\.Any\s*\(/g },
  { key: 'linq_sum', label: 'Sum', icon: '➕', description: '合計を計算する(LINQ)。', pattern: /\.Sum\s*\(/g },
  { key: 'linq_count', label: 'Count', icon: '🧮', description: '要素数を数える(LINQ)。', pattern: /\.Count\s*\(/g },
  { key: 'linq_aggregate', label: 'Aggregate', icon: '🧩', description: '要素を1つの値にまとめ上げる(LINQ)。', pattern: /\.Aggregate\s*\(/g },
  { key: 'property_getset', label: 'プロパティ(get/set)', icon: '🏷️', description: '値の読み書きを関数のように扱えるプロパティ。', pattern: /\{\s*get;\s*set;\s*\}/g },
  { key: 'var_kw', label: 'var', icon: '🤖', description: 'コンパイラに型を自動推論させるキーワード。', pattern: /\bvar\s+\w+\s*=/g },
  { key: 'nullable_type', label: 'null許容型(?)', icon: '❔', description: 'nullを許容する型を表す記法(?)。', pattern: /\w\?\s+\w+\s*[=;]/g },
  { key: 'record_kw', label: 'record', icon: '📇', description: '値の比較や不変性を前提にしたデータ用の型(record)。', pattern: /\brecord\s+\w/g },
  { key: 'delegate_kw', label: 'delegate', icon: '📮', description: 'メソッドを値として扱うための型。', pattern: /\bdelegate\s+\w/g },
  { key: 'event_kw', label: 'event', icon: '🔔', description: '何かが起きたことを他に知らせる仕組み。', pattern: /\bevent\s+\w/g },
  { key: 'attribute_syntax', label: '属性([Attribute])', icon: '🏷️', description: 'クラスやメソッドにメタ情報を付与する記法([Attribute])。', pattern: /^\s*\[[A-Z]\w*(\(.*\))?\]/gm },
  { key: 'string_interpolation_cs', label: '文字列補間($"")', icon: '💬', description: '文字列の中に変数を埋め込んで書ける記法($"...")。', pattern: /\$"/g },
  { key: 'null_conditional', label: 'null条件演算子(?.)', icon: '❓', description: '途中の値がnullでも安全にアクセスする記法(?.)。', pattern: /\?\./g },
  { key: 'task_type', label: 'Task<T>', icon: '⏳', description: '非同期処理の結果を表す型。', pattern: /\bTask</g },
  { key: 'dispose_pattern', label: 'Dispose', icon: '♻️', description: '使い終わったリソースを解放するためのメソッド。', pattern: /\bDispose\s*\(/g },
  { key: 'using_statement', label: 'usingブロック', icon: '🧹', description: 'リソースの後片付け(Dispose)を自動化するブロック。', pattern: /\busing\s*\(/g },
  { key: 'static_readonly', label: 'static readonly', icon: '🔒', description: 'クラス全体で共有される、変更不可の値。', pattern: /\bstatic\s+readonly\b/g },
];

// gate: 'import'ならそのライブラリキーが実際にimportされていた場合だけ、
// { languages: [...] }なら解析対象ファイルの言語がそれに含まれる場合だけ走査する。
const GROUPS = {
  react: { label: 'React', icon: '⚛️', gate: 'import', objects: REACT_OBJECTS },
  pandas: { label: 'pandas', icon: '🐼', gate: 'import', objects: PANDAS_OBJECTS },
  numpy: { label: 'NumPy', icon: '🔢', gate: 'import', objects: NUMPY_OBJECTS },
  express: { label: 'Express', icon: '🚂', gate: 'import', objects: EXPRESS_OBJECTS },
  electron: { label: 'Electron', icon: '⚡', gate: 'import', objects: ELECTRON_OBJECTS },
  javascript: { label: 'JavaScript', icon: '📜', gate: { languages: ['javascript', 'typescript'] }, objects: JAVASCRIPT_OBJECTS },
  typescript: { label: 'TypeScript', icon: '🔷', gate: { languages: ['typescript'] }, objects: TYPESCRIPT_OBJECTS },
  cpp: { label: 'C++', icon: '➕', gate: { languages: ['cpp'] }, objects: CPP_OBJECTS },
  csharp: { label: 'C#', icon: '♯', gate: { languages: ['csharp'] }, objects: CSHARP_OBJECTS },
};

// importされたライブラリのキー一覧と解析対象の言語から、該当するすべてのグループを走査して
// 具体的なオブジェクト(フック/メソッド/構文など)の使用状況を数える
function detectGroupObjects({ languageId, importedLibraryKeys }, code) {
  const results = [];
  for (const [groupKey, group] of Object.entries(GROUPS)) {
    const applies = group.gate === 'import' ? importedLibraryKeys.has(groupKey) : group.gate.languages.includes(languageId);
    if (!applies) continue;
    for (const obj of group.objects) {
      const matches = code.match(obj.pattern);
      if (matches && matches.length > 0) results.push({ groupKey, key: obj.key, count: matches.length });
    }
  }
  return results;
}

module.exports = { GROUPS, detectGroupObjects };
